version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "data_base:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: hitman
      POSTGRES_DB: blog_dev
volumes:
  data_base:
